# @package models.background_upscaler
_target_: discoverex.adapters.outbound.models.realesrgan_background_upscaler.RealEsrganBackgroundUpscalerModel
model_name: 4x-UltraSharp
scale: 4
weights_repo_id: MidnightRunner/Misc
weights_filename: 4x-UltraSharp.pth
device: ${runtime.model_runtime.device}
dtype: ${runtime.model_runtime.dtype}
tile: 512
tile_pad: 16
pre_pad: 0
strict_runtime: true
weights_cache_dir: .cache/realesrgan
model_cache_dir: ${oc.env:MODEL_CACHE_DIR,""}
hf_home: ${oc.env:HF_HOME,""}
